using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace APP_MU.Models.DatabaseQuerys
{
    class Querys
    {
        //mu_online_login
        public string world_server =
            "INSERT INTO `world_server` (`server`, `world`) VALUES (" + CreaterServer.code + ", 0), (" + CreaterServer.code + ", 1), (" + CreaterServer.code + ", 2), (" + CreaterServer.code + ", 3), (" + CreaterServer.code + ", 4), (" + CreaterServer.code + ", 5), (" + CreaterServer.code + ", 6), (" + CreaterServer.code + ", 7), (" + CreaterServer.code + ", 8), (" + CreaterServer.code + ", 9), (" + CreaterServer.code + ", 10), (" + CreaterServer.code + ", 11), (" + CreaterServer.code + ", 12), (" + CreaterServer.code + ", 13), (" + CreaterServer.code + ", 14), (" + CreaterServer.code + ", 15), (" + CreaterServer.code + ", 16), (" + CreaterServer.code + ", 17), (" + CreaterServer.code + ", 18), (" + CreaterServer.code + ", 19), (" + CreaterServer.code + ", 20), (" + CreaterServer.code + ", 21), (" + CreaterServer.code + ", 22), (" + CreaterServer.code + ", 23), (" + CreaterServer.code + ", 24), (" + CreaterServer.code + ", 25), (" + CreaterServer.code + ", 26), (" + CreaterServer.code + ", 27), (" + CreaterServer.code + ", 28), (" + CreaterServer.code + ", 29), (" + CreaterServer.code + ", 30), (" + CreaterServer.code + ", 31), (" + CreaterServer.code + ", 32), (" + CreaterServer.code + ", 33), (" + CreaterServer.code + ", 34), (" + CreaterServer.code + ", 35), (" + CreaterServer.code + ", 36), (" + CreaterServer.code + ", 37), (" + CreaterServer.code + ", 38), (" + CreaterServer.code + ", 39), (" + CreaterServer.code + ", 40), (" + CreaterServer.code + ", 41), (" + CreaterServer.code + ", 42), (" + CreaterServer.code + ", 43), (" + CreaterServer.code + ", 44), (" + CreaterServer.code + ", 45), (" + CreaterServer.code + ", 46), (" + CreaterServer.code + ", 47), (" + CreaterServer.code + ", 48), (" + CreaterServer.code + ", 49), (" + CreaterServer.code + ", 50), (" + CreaterServer.code + ", 51), (" + CreaterServer.code + ", 52), (" + CreaterServer.code + ", 53), (" + CreaterServer.code + ", 54), (" + CreaterServer.code + ", 55), (" + CreaterServer.code + ", 56), (" + CreaterServer.code + ", 57), (" + CreaterServer.code + ", 58), (" + CreaterServer.code + ", 59), (" + CreaterServer.code + ", 60), (" + CreaterServer.code + ", 61), (" + CreaterServer.code + ", 62), (" + CreaterServer.code + ", 63), (" + CreaterServer.code + ", 64), (" + CreaterServer.code + ", 65), (" + CreaterServer.code + ", 66), (" + CreaterServer.code + ", 67), (" + CreaterServer.code + ", 68), (" + CreaterServer.code + ", 69), (" + CreaterServer.code + ", 70), (" + CreaterServer.code + ", 71), (" + CreaterServer.code + ", 72), (" + CreaterServer.code + ", 73), (" + CreaterServer.code + ", 74), (" + CreaterServer.code + ", 75), (" + CreaterServer.code + ", 76), (" + CreaterServer.code + ", 77), (" + CreaterServer.code + ", 78), (" + CreaterServer.code + ", 79), (" + CreaterServer.code + ", 80), (" + CreaterServer.code + ", 81), (" + CreaterServer.code + ", 82), (" + CreaterServer.code + ", 83), (" + CreaterServer.code + ", 84), (" + CreaterServer.code + ", 85), (" + CreaterServer.code + ", 86), (" + CreaterServer.code + ", 87), (" + CreaterServer.code + ", 88), (" + CreaterServer.code + ", 89), (" + CreaterServer.code + ", 90), (" + CreaterServer.code + ", 91), (" + CreaterServer.code + ", 92), (" + CreaterServer.code + ", 93), (" + CreaterServer.code + ", 94), (" + CreaterServer.code + ", 95), (" + CreaterServer.code + ", 96), (" + CreaterServer.code + ", 97), (" + CreaterServer.code + ", 98), (" + CreaterServer.code + ", 99), (" + CreaterServer.code + ", 100), (" + CreaterServer.code + ", 101), (" + CreaterServer.code + ", 102), (" + CreaterServer.code + ", 103), (" + CreaterServer.code + ", 104), (" + CreaterServer.code + ", 105), (" + CreaterServer.code + ", 106), (" + CreaterServer.code + ", 107), (" + CreaterServer.code + ", 108), (" + CreaterServer.code + ", 109), (" + CreaterServer.code + ", 110), (" + CreaterServer.code + ", 111), (" + CreaterServer.code + ", 112), (" + CreaterServer.code + ", 113), (" + CreaterServer.code + ", 114), (" + CreaterServer.code + ", 115), (" + CreaterServer.code + ", 116), (" + CreaterServer.code + ", 117), (" + CreaterServer.code + ", 118), (" + CreaterServer.code + ", 119), (" + CreaterServer.code + ", 120), (" + CreaterServer.code + ", 121), (" + CreaterServer.code + ", 122), (" + CreaterServer.code + ", 123), (" + CreaterServer.code + ", 124), (" + CreaterServer.code + ", 125), (" + CreaterServer.code + ", 126), (" + CreaterServer.code + ", 127), (" + CreaterServer.code + ", 128), (" + CreaterServer.code + ", 129), (" + CreaterServer.code + ", 130), (" + CreaterServer.code + ", 131), (" + CreaterServer.code + ", 132), (" + CreaterServer.code + ", 133);";

        //mu_game
        public string settings =
        "INSERT INTO mu_game.settings(server_id, `key`, value) VALUES " +
        "(" + CreaterServer.code + ", 'Account.ConnectCheckTime', '180')," +
        "(" + CreaterServer.code + ", 'Account.DarkLordCreate', '1')," +
        "(" + CreaterServer.code + ", 'Account.DisconnectTime', '5')," +
        "(" + CreaterServer.code + ", 'Account.GameCloseTime', '5')," +
        "(" + CreaterServer.code + ", 'Account.GrowLancerCreate', '1')," +
        "(" + CreaterServer.code + ", 'Account.MagicGladiatorCreate', '1')," +
        "(" + CreaterServer.code + ", 'Account.MaxLoginAttempts', '25')," +
        "(" + CreaterServer.code + ", 'Account.RageFighterCreate', '1')," +
        "(" + CreaterServer.code + ", 'Account.ServerMoveKickTime', '5')," +
        "(" + CreaterServer.code + ", 'Account.Warehouse.GetMoney', '1')," +
        "(" + CreaterServer.code + ", 'Account.Warehouse.Lock', '1')," +
        "(" + CreaterServer.code + ", 'Account.Warehouse.MaxMoney', '9999999999')," +
        "(" + CreaterServer.code + ", 'Account.Warehouse.SaveMoney', '1')," +
        "(" + CreaterServer.code + ", 'AntiHack.CoordinateAttackCheck', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.CoordinateVerify', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.CoordinateVerifyTime', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillContinue', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillCount', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillCountContinue', '2')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillHeadcodeCheck', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillKick', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.SkillLogCount', '3')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheck1', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheck2', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheck3', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheck4', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheck5', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheckDistance1', '0')," +
        "(" + CreaterServer.code + ", 'AntiHack.WalkCheckError1', '0')," +
        "(" + CreaterServer.code + ", 'AntiMacro.ComboEnabled', '1')," +
        "(" + CreaterServer.code + ", 'AntiMacro.ComboTime', '0')," +
        "(" + CreaterServer.code + ", 'AntiMacro.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'AntiMacro.Time', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.DamageReductionAlly', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.DamageReductionEnemy', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.MinGuilds', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.RegisterMaxMembers', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.RegisterMinMembers', '0')," +
        "(" + CreaterServer.code + ", 'ArkaWar.Server', '0')," +
        "(" + CreaterServer.code + ", 'AttackRangeTolerance', '1')," +
        "(" + CreaterServer.code + ", 'AttackTime.NullKick', '1')," +
        "(" + CreaterServer.code + ", 'Barracks.MoveCost', '10000')," +
        "(" + CreaterServer.code + ", 'Barracks.MoveEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Barracks.MoveMinLevel', '280')," +
        "(" + CreaterServer.code + ", 'Barracks.MoveParty', '1')," +
        "(" + CreaterServer.code + ", 'BloodCastle.DeliverWeaponTime', '900')," +
        "(" + CreaterServer.code + ", 'BloodCastle.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'BloodCastle.RewardScore', '1')," +
        "(" + CreaterServer.code + ", 'BloodCastle.SkillRushCheck', '1')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerDir', '/Data/InGameShopBanner/')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerDirTest', '/Data/InGameShopScript/')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerIp', '')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerMonth', '002')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerNumber', '000')," +
        "(" + CreaterServer.code + ", 'CashShop.BannerYear', '2015')," +
        "(" + CreaterServer.code + ", 'CashShop.CoinUpdateTime', '10')," +
        "(" + CreaterServer.code + ", 'CashShop.DiscountDate', '0')," +
        "(" + CreaterServer.code + ", 'CashShop.DiscountGP', '0')," +
        "(" + CreaterServer.code + ", 'CashShop.DiscountWC', '0')," +
        "(" + CreaterServer.code + ", 'CashShop.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'CashShop.GiftUpdateTime', '0')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemDir', '/Data/InGameShopScript/')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemDirTest', '/Data/InGameShopScript/')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemIp', '')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemListMonth', '001')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemListNumber', '000')," +
        "(" + CreaterServer.code + ", 'CashShop.ItemListYear', '2020')," +
        "(" + CreaterServer.code + ", 'CashShop.SafeZone', '0')," +
        "(" + CreaterServer.code + ", 'CashShop.UseJoin', '1')," +
        "(" + CreaterServer.code + ", 'CastleDeep.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'CastleSiege.CrownTime', '120')," +
        "(" + CreaterServer.code + ", 'CastleSiege.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'CastleSiege.LordMixMax', '1')," +
        "(" + CreaterServer.code + ", 'CastleSiege.MachineEnabled', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.ParticipantRewardMinutes', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.ReduceDamageDifSide', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.ReduceDamageSameSide', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.RegisterEnabled', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.RegisterMinLevel', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.RegisterMinMembers', '0')," +
        "(" + CreaterServer.code + ", 'CastleSiege.RegisterSignEnabled', '0')," +
        "(" + CreaterServer.code + ", 'ChaosCastle.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'ChaosCastle.SurvivalMaxPerPC', '10')," +
        "(" + CreaterServer.code + ", 'ChaosCastle.SurvivalOfTheFittestEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.AGAutorecuperationCount', '50')," +
        "(" + CreaterServer.code + ", 'Character.AGAutorecuperationCountRest', '10')," +
        "(" + CreaterServer.code + ", 'Character.AGAutorecuperationEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.AGAutorecuperationMaxLevel', '1200')," +
        "(" + CreaterServer.code + ", 'Character.AutoSaveOfflineTime', '10')," +
        "(" + CreaterServer.code + ", 'Character.AutosaveTime', '5')," +
        "(" + CreaterServer.code + ", 'Character.DieExperienceDecrease', '100')," +
        "(" + CreaterServer.code + ", 'Character.DieZenDecrease', '50')," +
        "(" + CreaterServer.code + ", 'Character.DKDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.DKDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.DLDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.DLDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.DWDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.DWDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.FEDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.FEDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.GCDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.GCDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.GLDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.GLDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.HeroCount', '10')," +
        "(" + CreaterServer.code + ", 'Character.HeroTime', '1000')," +
        "(" + CreaterServer.code + ", 'Character.HPAutorecuperationCount', '50')," +
        "(" + CreaterServer.code + ", 'Character.HPAutorecuperationCountRest', '1')," +
        "(" + CreaterServer.code + ", 'Character.HPAutorecuperationEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.HPAutorecuperationMaxLevel', '1200')," +
        "(" + CreaterServer.code + ", 'Character.MaxAgility', '65765')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedDK', '288')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedDL', '450')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedDW', '284')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedELF', '275')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedGC', '280')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedGL', '273')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedMG', '351')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedRF', '441')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedRW', '274')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedSL', '384')," +
        "(" + CreaterServer.code + ", 'Character.MaxAttackSpeedSUM', '188')," +
        "(" + CreaterServer.code + ", 'Character.MaxEnergy', '65765')," +
        "(" + CreaterServer.code + ", 'Character.MaxExpandedInventory', '128')," +
        "(" + CreaterServer.code + ", 'Character.MaxLeadership', '65765')," +
        "(" + CreaterServer.code + ", 'Character.MaxLevelMajestic', '400')," +
        "(" + CreaterServer.code + ", 'Character.MaxLevelMaster', '400')," +
        "(" + CreaterServer.code + ", 'Character.MaxLevelNormal', '400')," +
        "(" + CreaterServer.code + ", 'Character.MaxStrength', '65765')," +
        "(" + CreaterServer.code + ", 'Character.MaxVitality', '65765')," +
        "(" + CreaterServer.code + ", 'Character.MaxZen', '9999999999')," +
        "(" + CreaterServer.code + ", 'Character.MGDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.MGDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.MinMonsterLevelMajestic', '0')," +
        "(" + CreaterServer.code + ", 'Character.MinMonsterLevelMaster', '0')," +
        "(" + CreaterServer.code + ", 'Character.MPAutorecuperationCount', '0')," +
        "(" + CreaterServer.code + ", 'Character.MPAutorecuperationCountRest', '0')," +
        "(" + CreaterServer.code + ", 'Character.MPAutorecuperationEnabled', '0')," +
        "(" + CreaterServer.code + ", 'Character.MPAutorecuperationMaxLevel', '0')," +
        "(" + CreaterServer.code + ", 'Character.MultiAttackFireScream', '1')," +
        "(" + CreaterServer.code + ", 'Character.MultiAttackPenetration', '1')," +
        "(" + CreaterServer.code + ", 'Character.MurderCount', '3')," +
        "(" + CreaterServer.code + ", 'Character.MurderLimitCount', '0')," +
        "(" + CreaterServer.code + ", 'Character.MurderTime', '300')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttack', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackBuffItem', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackCount', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackDetailAutoloot', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackFlag', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackGoblinPointsGain', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackIPCount', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackMaxLevel', '1200')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackMinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackMonsterAICheck', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackOnDisconnect', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackTime', '9999')," +
        "(" + CreaterServer.code + ", 'Character.OfflineAttackZenLoot', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineCloseWhenWrongLevel', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineDieDisconnectTime', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineDisconnectTime', '0')," +
        "(" + CreaterServer.code + ", 'Character.OfflineMove', '1')," +
        "(" + CreaterServer.code + ", 'Character.OfflineSkillTime', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDrop', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDrop380', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDropAncient', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDropExcellent', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDropHarmony', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDropItemMaxLevel', '1')," +
        "(" + CreaterServer.code + ", 'Character.PKItemDropMinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Character.PKWarpCostIncrease', '0')," +
        "(" + CreaterServer.code + ", 'Character.PVPEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.PVPMinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Character.RepairButton.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.RepairButton.MinLevel', '1')," +
        "(" + CreaterServer.code + ", 'Character.RFDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.RFDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.RWDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.RWDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.SD.AttackSuccessRate', '100')," +
        "(" + CreaterServer.code + ", 'Character.SD.ComboMissInit', '100')," +
        "(" + CreaterServer.code + ", 'Character.SD.DamageToShield', '100')," +
        "(" + CreaterServer.code + ", 'Character.SDAutorecuperationCount', '10')," +
        "(" + CreaterServer.code + ", 'Character.SDAutorecuperationCountRest', '10')," +
        "(" + CreaterServer.code + ", 'Character.SDAutorecuperationEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.SDAutorecuperationMaxLevel', '1200')," +
        "(" + CreaterServer.code + ", 'Character.SelfDefenseEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Character.SelfDefenseTime', '10')," +
        "(" + CreaterServer.code + ", 'Character.SLDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.SLDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'Character.SMDamageModPVE', '100')," +
        "(" + CreaterServer.code + ", 'Character.SMDamageModPVP', '100')," +
        "(" + CreaterServer.code + ", 'CheatScan.Ban', '0')," +
        "(" + CreaterServer.code + ", 'CheatScan.Count', '0')," +
        "(" + CreaterServer.code + ", 'CheatScan.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'CheatScan.Kick', '0')," +
        "(" + CreaterServer.code + ", 'CheatScan.Time', '0')," +
        "(" + CreaterServer.code + ", 'ComboCheck.Count', '0')," +
        "(" + CreaterServer.code + ", 'ComboCheck.DatabaseLog', '0')," +
        "(" + CreaterServer.code + ", 'ComboCheck.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'ComboCheck.Kick', '0')," +
        "(" + CreaterServer.code + ", 'ComboCheck.Stop', '0')," +
        "(" + CreaterServer.code + ", 'ComboCheck.TimeDiff', '0')," +
        "(" + CreaterServer.code + ", 'Command.AddStat.Cost', '0')," +
        "(" + CreaterServer.code + ", 'Command.AddStat.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Command.AddStat.MinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Command.Gold.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Command.Gold.MaxDays', '0')," +
        "(" + CreaterServer.code + ", 'Command.Gold.Price', '0')," +
        "(" + CreaterServer.code + ", 'Command.Master', '1')," +
        "(" + CreaterServer.code + ", 'Command.Post.Cost', '0')," +
        "(" + CreaterServer.code + ", 'Command.Post.Delay', '0')," +
        "(" + CreaterServer.code + ", 'Command.Post.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Command.Post.Head', '$name: [POST][$server]: $message')," +
        "(" + CreaterServer.code + ", 'Command.Post.MinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Command.Post.Type', '0')," +
        "(" + CreaterServer.code + ", 'Command.Refresh.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'Command.Refresh.Time', '0')," +
        "(" + CreaterServer.code + ", 'Common.FenrirRepairRate', '100')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.ExeMaxOption', '2')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.ExeMinOption', '1')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.LuckRateExe', '0.5')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.LuckRateNormal', '1')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.RateExe', '1')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.RateNormal', '1.5')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.SkillRateNormal', '5')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket1RateExe', '5')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket1RateNormal', '10')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket2RateExe', '4')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket2RateNormal', '9')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket3RateExe', '3')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket3RateNormal', '8')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket4RateExe', '2')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket4RateNormal', '7')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket5RateExe', '1')," +
        "(" + CreaterServer.code + ", 'Common.ItemDrop.Socket5RateNormal', '6')," +
        "(" + CreaterServer.code + ", 'Common.ItemDurationTime', '59')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.Max', '10')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.MaxRate', '10')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.RateAncient', '5')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.RateExe', '2')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.RateNormal', '5')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.RateSocket', '1')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.Reset', '5')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.ResetRate', '5')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfLife.ResetWarning', '')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfSoul.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfSoul.Rate', '10')," +
        "(" + CreaterServer.code + ", 'Common.JewelOfSoul.RateLuck', '5')," +
        "(" + CreaterServer.code + ", 'Common.LootingTime', '59')," +
        "(" + CreaterServer.code + ", 'Common.PersonalMerchantShop', '1')," +
        "(" + CreaterServer.code + ", 'Crywolf.AIChange.Time', '300')," +
        "(" + CreaterServer.code + ", 'Crywolf.Altar.ContractValidationTime', '10')," +
        "(" + CreaterServer.code + ", 'Crywolf.Altar.ContractWaitTime', '0')," +
        "(" + CreaterServer.code + ", 'Crywolf.Altar.MaxContract', '5')," +
        "(" + CreaterServer.code + ", 'Crywolf.Altar.MinLevel', '150')," +
        "(" + CreaterServer.code + ", 'Crywolf.Altar.Score', '6000')," +
        "(" + CreaterServer.code + ", 'Crywolf.Balgass.StartTime', '600')," +
        "(" + CreaterServer.code + ", 'Crywolf.Benefit.Apply', '1')," +
        "(" + CreaterServer.code + ", 'Crywolf.Benefit.KundunRefill', '10')," +
        "(" + CreaterServer.code + ", 'Crywolf.Benefit.MonsterHp', '10')," +
        "(" + CreaterServer.code + ", 'Crywolf.Benefit.PlusRate', '10')," +
        "(" + CreaterServer.code + ", 'Crywolf.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Crywolf.Penalty.Apply', '1')," +
        "(" + CreaterServer.code + ", 'Crywolf.Penalty.DropGem', '10')," +
        "(" + CreaterServer.code + ", 'Crywolf.Penalty.ExpGain', '10')," +
        "(" + CreaterServer.code + ", 'CustomBoss.SummonCount', '2')," +
        "(" + CreaterServer.code + ", 'CustomBoss.SummonDespawnTime', '0')," +
        "(" + CreaterServer.code + ", 'CustomBoss.SummonTime', '1000')," +
        "(" + CreaterServer.code + ", 'DevilSquare.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Doppelganger.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Doppelganger.MonsterSpeed', '0')," +
        "(" + CreaterServer.code + ", 'Doppelganger.PKCheck', '0')," +
        "(" + CreaterServer.code + ", 'Doppelganger.PKLevelMax', '0')," +
        "(" + CreaterServer.code + ", 'Duel.BuffDisabled', '0')," +
        "(" + CreaterServer.code + ", 'Duel.Classic', '0')," +
        "(" + CreaterServer.code + ", 'Duel.Damage', '0')," +
        "(" + CreaterServer.code + ", 'Duel.Duration', '0')," +
        "(" + CreaterServer.code + ", 'Duel.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'Duel.MaxWaitInterval', '0')," +
        "(" + CreaterServer.code + ", 'Duel.MinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Duel.MuunDisabled', '0')," +
        "(" + CreaterServer.code + ", 'Duel.PentagramDisabled', '0')," +
        "(" + CreaterServer.code + ", 'Duel.RequiredZen', '0')," +
        "(" + CreaterServer.code + ", 'Duel.RoundStandby', '0')," +
        "(" + CreaterServer.code + ", 'Duel.StandByTime', '0')," +
        "(" + CreaterServer.code + ", 'Duel.TestLevel', '0')," +
        "(" + CreaterServer.code + ", 'Dungeon.Duration', '300')," +
        "(" + CreaterServer.code + ", 'Dungeon.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Dungeon.EndGate', '50')," +
        "(" + CreaterServer.code + ", 'Dungeon.GAP', '10')," +
        "(" + CreaterServer.code + ", 'Dungeon.MaxPerPC', '10')," +
        "(" + CreaterServer.code + ", 'Dungeon.MinParty', '0')," +
        "(" + CreaterServer.code + ", 'Dungeon.SilverChestMonster', '10')," +
        "(" + CreaterServer.code + ", 'Dungeon.SimpleTrapDamage', '10')," +
        "(" + CreaterServer.code + ", 'Dungeon.SimpleTrapTime', '10')," +
        "(" + CreaterServer.code + ", 'Dungeon.WaitTime', '10')," +
        "(" + CreaterServer.code + ", 'DungeonRace.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'DungeonRace.Reward', '6000')," +
        "(" + CreaterServer.code + ", 'Event.KillRankingEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Event.TimeRankingEnabled', '1')," +
        "(" + CreaterServer.code + ", 'EventInventory.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Evomon.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Evomon.PartyReward', '1')," +
        "(" + CreaterServer.code + ", 'Evomon.PartySpecialReward', '1')," +
        "(" + CreaterServer.code + ", 'Evomon.Send', '1')," +
        "(" + CreaterServer.code + ", 'Friend.AddMinLevel', '1')," +
        "(" + CreaterServer.code + ", 'Friend.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Friend.MailCost', '100')," +
        "(" + CreaterServer.code + ", 'Friend.MailEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Friend.MailUpdateInterval', '10')," +
        "(" + CreaterServer.code + ", 'GameServer.Active', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.AdministratorAuthorization', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeBlock', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeBoxCheckTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeBoxEnabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeBoxRemove', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeBoxServer', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiDupeKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiFloodCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiFloodKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiSpam.Count', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiSpam.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiSpam.MuteTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AntiSpam.Time', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackDebuffFirstHit', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSafeCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSafeEnabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSafeKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSafeTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedRange', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackSpeedSendTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AttackStunCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.AuthServerReconnectEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.AuthServerReconnectTime', '5')," +
        "(" + CreaterServer.code + ", 'GameServer.AutoLoginEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.AutoLoginRandomTime', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.AutoLoginTime', '5')," +
        "(" + CreaterServer.code + ", 'GameServer.BossStackCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ChannelChangeEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ChaosMachineSafeItemMove', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.CharacterOnlineOnLogin', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ConnectServerReconnectEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ConnectServerReconnectTime', '5')," +
        "(" + CreaterServer.code + ", 'GameServer.ConnectTimeKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.CriticalDamageRateLimit', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.DarkRavenAutorepair', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.DebuffStopCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.Debug', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.DecreaseDamageRateLimit', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.DobleFrustrum', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.DupeCompleteBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.DuplicatedCharacterCheck', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ElfSkillWeaponCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ElfSoldierMaxLevel', '120')," +
        "(" + CreaterServer.code + ", 'GameServer.ElfSoldierRemoveOnDie', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ElfSoldierUpdate', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ExcellentDamageRateLimit', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.FereaBossHPRecoveryCount', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.FereaBossHPRecoveryTime', '10')," +
        "(" + CreaterServer.code + ", 'GameServer.FullInventoryToGremoryCase', '120')," +
        "(" + CreaterServer.code + ", 'GameServer.GateHandle', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckEnabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckFrameCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckFullBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckLoopTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckResetTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HackCheckTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.HostilCancelCommand', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.IgnoreDefenseRateLimit', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.InactiveTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.InventoryMountTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemBuffCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemBuyLogDB', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemDropLogDB', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemLootLogDB', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemSellLogDB', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ItemSplitEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.JoinItemsWithExpireTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.LogDB.PersonalStore', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.LogDB.Trade', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.LoginDiskSerialMacCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.LogRecvPacket', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.LogSendPacket', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.LuckyItemMixCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MajesticExperienceRate', '200')," +
        "(" + CreaterServer.code + ", 'GameServer.MajesticZenRate', '30')," +
        "(" + CreaterServer.code + ", 'GameServer.MasterExperienceRate', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.MasterZenRate', '20')," +
        "(" + CreaterServer.code + ", 'GameServer.MaxMonsters', '999999')," +
        "(" + CreaterServer.code + ", 'GameServer.MaxPlayers', '30')," +
        "(" + CreaterServer.code + ", 'GameServer.MaxSocketWear', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MonsterAttackWallCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MonsterStopAction', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MonsterTeleportOutOfRange', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MonsterViewportControl', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.MultiAttackSkillCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.NormalExperienceRate', '50')," +
        "(" + CreaterServer.code + ", 'GameServer.NormalMonsterMovement', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.NormalZenRate', '1.5')," +
        "(" + CreaterServer.code + ", 'GameServer.PentagramErrtelFix', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PersonalStoreLockSamePC', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PetComboExperience', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PKBossServer', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PKBossTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PostManager.Count', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PostManager.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PostManagerMAC.Count', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.PostManagerMAC.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.RecvPacketQueueKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.RecvPacketQueueMax', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ReflectDamageRateLimit', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ReflectFix', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.ReservedMonsters', '500')," +
        "(" + CreaterServer.code + ", 'GameServer.ReservedPlayers', '3')," +
        "(" + CreaterServer.code + ", 'GameServer.SecurityCode', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.Serial', 'jw45af7xf4wxj198')," +
        "(" + CreaterServer.code + ", 'GameServer.ServerLinkServerReconnectEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ServerLinkServerReconnectTime', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ServerWarpTransactionCheck1', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ServerWarpTransactionCheck2', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.ServerWarpTransactionCheck3', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.SessionTimeout', '120')," +
        "(" + CreaterServer.code + ", 'GameServer.ShieldDefenseRateLimit', '100')," +
        "(" + CreaterServer.code + ", 'GameServer.ShutdownCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.SkillBlessStrenghtenerFix', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.SkillCheckEnabled', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.SpawnMonsterTime', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.StackExpirableItemsOnLoot', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TempDualWeaponDmg1', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TempDualWeaponDmg2', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TestEnabled', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TestKey', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TestKickTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TimeCheck', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TimeCheckLevelMax', '-1')," +
        "(" + CreaterServer.code + ", 'GameServer.TimeCheckLevelMin', '-1')," +
        "(" + CreaterServer.code + ", 'GameServer.TimeCheckTime', '-1')," +
        "(" + CreaterServer.code + ", 'GameServer.TradeInterfaceCancelBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.TransactionRollbackCurrency', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.Version', '1.07.17')," +
        "(" + CreaterServer.code + ", 'GameServer.ViewportFrustrum', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WalkSpeedBan', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WalkSpeedCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WalkSpeedDistance', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WalkSpeedFix', '1')," +
        "(" + CreaterServer.code + ", 'GameServer.WalkSpeedKick', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WelcomeMessage', '')," +
        "(" + CreaterServer.code + ", 'GameServer.WelcomeNotice', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WhisperLog', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WrongDecryptCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WrongDecryptTime', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WrongSerialCount', '0')," +
        "(" + CreaterServer.code + ", 'GameServer.WrongSerialTime', '0')," +
        "(" + CreaterServer.code + ", 'Gen.ChangeFamilyTime', '0')," +
        "(" + CreaterServer.code + ", 'Gen.JoinMinLevel', '0')," +
        "(" + CreaterServer.code + ", 'Gen.Penalization', '0')," +
        "(" + CreaterServer.code + ", 'Gen.PenalizationCount', '0')," +
        "(" + CreaterServer.code + ", 'Gen.PenalizationTime', '0')," +
        "(" + CreaterServer.code + ", 'GLElementalDamageFix', '1')," +
        "(" + CreaterServer.code + ", 'GoblinPoint.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'GoblinPoint.KillTime', '30')," +
        "(" + CreaterServer.code + ", 'GoblinPoint.RequiredTime', '30')," +
        "(" + CreaterServer.code + ", 'GoblinPoint.RequiredTimeOffline', '10')," +
        "(" + CreaterServer.code + ", 'GremoryCase.FreeSpaceCheck', '1')," +
        "(" + CreaterServer.code + ", 'Guardian.DisassembleItemBag', '1')," +
        "(" + CreaterServer.code + ", 'Guild.Alliance.CastleSiegeCheck', '0')," +
        "(" + CreaterServer.code + ", 'Guild.Alliance.Gens', '0')," +
        "(" + CreaterServer.code + ", 'Guild.Alliance.Max', '0')," +
        "(" + CreaterServer.code + ", 'Guild.Alliance.MinMembers', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.Duration', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.GoalPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.KillAssistantPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.KillBattlePoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.KillMasterPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.KillPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.BattleSoccer.MaxScore', '0')," +
        "(" + CreaterServer.code + ", 'Guild.CreateGens', '0')," +
        "(" + CreaterServer.code + ", 'Guild.CreateMinLevel', '220')," +
        "(" + CreaterServer.code + ", 'Guild.Delete', '1')," +
        "(" + CreaterServer.code + ", 'Guild.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Guild.Hostil.EventKill', '0')," +
        "(" + CreaterServer.code + ", 'Guild.JoinGens', '0')," +
        "(" + CreaterServer.code + ", 'Guild.MaxWaitInterval', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Guild.War.IntervalTime', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.KillAssistantPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.KillBattlePoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.KillMasterPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.KillPoints', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.Max', '0')," +
        "(" + CreaterServer.code + ", 'Guild.War.MaxPoints', '999999')," +
        "(" + CreaterServer.code + ", 'Guild.War.MaxWaitInterval', '0')," +
        "(" + CreaterServer.code + ", 'GuildScore.ArkaWar', '0')," +
        "(" + CreaterServer.code + ", 'GuildScore.CastleSiege', '0')," +
        "(" + CreaterServer.code + ", 'GuildScore.CastleSiegeMembers', '0')," +
        "(" + CreaterServer.code + ", 'HappyHour.DropAdd', '100')," +
        "(" + CreaterServer.code + ", 'HappyHour.ExperienceAdd', '200')," +
        "(" + CreaterServer.code + ", 'Harmony.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Harmony.OnAncient', '1')," +
        "(" + CreaterServer.code + ", 'Harmony.RefineRate', '60')," +
        "(" + CreaterServer.code + ", 'Harmony.SmeltExeRate', '20')," +
        "(" + CreaterServer.code + ", 'Harmony.SmeltNormalRate', '30')," +
        "(" + CreaterServer.code + ", 'Harmony.StrengthenRate', '50')," +
        "(" + CreaterServer.code + ", 'Harmony.StrengthenUpdateExeRate', '20')," +
        "(" + CreaterServer.code + ", 'Harmony.StrengthenUpdateNormalRate', '35')," +
        "(" + CreaterServer.code + ", 'Helper.AutoLootEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Helper.BuffItemUseCheck', '1')," +
        "(" + CreaterServer.code + ", 'Helper.LootEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Helper.PotionUseEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Helper.RepairEnabled', '1')," +
        "(" + CreaterServer.code + ", 'HuntingRecord.Clear', '1')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.Day', '-1')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.EndTime', '120')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.InParty', '0')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.MoveToPrevious', '0')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.PKCheck', '0')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.PKLevelMax', '0')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.PlayTime', '120')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.StandbyTime', '15')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.TeleportCheck', '1')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.TimeZone1', '200')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.TimeZone2', '200')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.TimeZone3', '200')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.TimeZone4', '200')," +
        "(" + CreaterServer.code + ", 'ImperialFortress.WalkCheck', '1')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate10', '70')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate11', '65')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate12', '60')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate13', '55')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate14', '45')," +
        "(" + CreaterServer.code + ", 'ItemUpgrade.SuccessRate15', '35')," +
        "(" + CreaterServer.code + ", 'JewelBingo.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'JewelBingo.RequiredTicket', '5')," +
        "(" + CreaterServer.code + ", 'JewelBingo.Reward', '100')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreD', '10')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreH', '5')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreNotMatched', '0')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreSpecialH', '30')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreSpecialV', '50')," +
        "(" + CreaterServer.code + ", 'JewelBingo.ScoreV', '25')," +
        "(" + CreaterServer.code + ", 'Kanturu.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Kanturu.MaxPlayers', '25')," +
        "(" + CreaterServer.code + ", 'Kanturu.Maya.IceStormRate', '3')," +
        "(" + CreaterServer.code + ", 'Kanturu.Maya.SkillTime', '7')," +
        "(" + CreaterServer.code + ", 'Kick.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'Kick.Type', '0')," +
        "(" + CreaterServer.code + ", 'Kundun.RefillHp', '1')," +
        "(" + CreaterServer.code + ", 'Kundun.RefillHpSec', '5')," +
        "(" + CreaterServer.code + ", 'Kundun.RefillTime', '3')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.DayFirstScore', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.GoblinScore', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.GoblinStage', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MissionTime', '15')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MoveBronze', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MoveGold', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MoveLegend', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MoveOnFail', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.MoveSilver', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.RequiredLevel', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.RequiredMaster', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.Server', '-1')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.StateDuration', '0')," +
        "(" + CreaterServer.code + ", 'LabyrinthOfDimensions.TimeScore', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.Classic', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.DamageReduction', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.Duration', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.HideCharacter', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.KillScore', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.LevelRange', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.MaxPerPC', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.MinLevel', '0')," +
        "(" + CreaterServer.code + ", 'LastManStanding.Server', '9999')," +
        "(" + CreaterServer.code + ", 'LastManStanding.WinScore', '0')," +
        "(" + CreaterServer.code + ", 'Log.DamagePVP', '0')," +
        "(" + CreaterServer.code + ", 'Log.DamagePVPToDB', '0')," +
        "(" + CreaterServer.code + ", 'LosttowerRace.Enabled', '999')," +
        "(" + CreaterServer.code + ", 'LosttowerRace.Reward', '')," +
        "(" + CreaterServer.code + ", 'LuckyItem.Fix', '0')," +
        "(" + CreaterServer.code + ", 'LuckyItem.FixCount', '0')," +
        "(" + CreaterServer.code + ", 'MajesticAddDamageNormal', '0')," +
        "(" + CreaterServer.code + ", 'MajesticSkillDamageNormal', '0')," +
        "(" + CreaterServer.code + ", 'MiniBomb.ClearScore', '1')," +
        "(" + CreaterServer.code + ", 'MiniBomb.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'MiniBomb.FailScore', '0')," +
        "(" + CreaterServer.code + ", 'MiniBomb.FoundedBombsScore', '100')," +
        "(" + CreaterServer.code + ", 'MiniBomb.RequiredTicket', '5')," +
        "(" + CreaterServer.code + ", 'MiniBomb.RevealScore', '5')," +
        "(" + CreaterServer.code + ", 'MiniBomb.Reward', '1000')," +
        "(" + CreaterServer.code + ", 'MiniBomb.WrongBombsScore', '100')," +
        "(" + CreaterServer.code + ", 'Mix.GreaterSpellStonePriceDivision', '0')," +
        "(" + CreaterServer.code + ", 'Mix.GreaterSpellStoneRate', '0')," +
        "(" + CreaterServer.code + ", 'Mix.LesserSpellStonePriceDivision', '0')," +
        "(" + CreaterServer.code + ", 'Mix.LesserSpellStoneRate', '0')," +
        "(" + CreaterServer.code + ", 'Mix.MediumSpellStonePriceDivision', '0')," +
        "(" + CreaterServer.code + ", 'Mix.MediumSpellStoneRate', '0')," +
        "(" + CreaterServer.code + ", 'Mix.SealedBloodAngelExcellentMax', '0')," +
        "(" + CreaterServer.code + ", 'Mix.SealedBloodAngelExcellentMin', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'MixRecovery.ErrtelMixFailCount', '1')," +
        "(" + CreaterServer.code + ", 'MixRecovery.ErrtelOnFail', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.ErrtelRemoveFailCount', '5')," +
        "(" + CreaterServer.code + ", 'MixRecovery.FailTime', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.PriceBless', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.PriceWC', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.Time', '0')," +
        "(" + CreaterServer.code + ", 'MixRecovery.Warning', '0')," +
        "(" + CreaterServer.code + ", 'MonsterSoul.DurationTime', '0')," +
        "(" + CreaterServer.code + ", 'MonsterSoul.PurchaseAmount', '0')," +
        "(" + CreaterServer.code + ", 'MossMerchant.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'MossMerchant.ItemBag.Bow', '')," +
        "(" + CreaterServer.code + ", 'MossMerchant.ItemBag.Scepter', '')," +
        "(" + CreaterServer.code + ", 'MossMerchant.ItemBag.Staff', '')," +
        "(" + CreaterServer.code + ", 'MossMerchant.ItemBag.Stick', '')," +
        "(" + CreaterServer.code + ", 'MossMerchant.ItemBag.Sword', '')," +
        "(" + CreaterServer.code + ", 'MuRoomy.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'MuRoomy.RewardMoneyAmount', '10000')," +
        "(" + CreaterServer.code + ", 'MuRoomy.SpecialEnabled', '10')," +
        "(" + CreaterServer.code + ", 'MuRoomy.TicketRequired', '5')," +
        "(" + CreaterServer.code + ", 'Muun.Attack.Delay', '1500')," +
        "(" + CreaterServer.code + ", 'Muun.Attack.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Muun.Attack.HitDelay', '200')," +
        "(" + CreaterServer.code + ", 'Muun.Attack.Range', '2')," +
        "(" + CreaterServer.code + ", 'Muun.DurabilityRate', '100')," +
        "(" + CreaterServer.code + ", 'Muun.EvolveBonus', '50')," +
        "(" + CreaterServer.code + ", 'Muun.EvolveBonusTime', '3600000')," +
        "(" + CreaterServer.code + ", 'Muun.MountTime', '10')," +
        "(" + CreaterServer.code + ", 'Network.BindIP', '0.0.0.0')," +
        "(" + CreaterServer.code + ", 'Network.MaxConnectionPerIP', '10')," +
        "(" + CreaterServer.code + ", 'NixiesLake.BattleTime', '15')," +
        "(" + CreaterServer.code + ", 'NixiesLake.BossRecoveryPercent', '30')," +
        "(" + CreaterServer.code + ", 'NixiesLake.BossRecoveryStandyTime', '10')," +
        "(" + CreaterServer.code + ", 'NixiesLake.BossRecoveryTime', '5')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ClosedTime', '30')," +
        "(" + CreaterServer.code + ", 'NixiesLake.Free', '1')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ItemBag1', '')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ItemBag2', '')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ItemBag3', '')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ItemBag4', '')," +
        "(" + CreaterServer.code + ", 'NixiesLake.ItemBag5', '')," +
        "(" + CreaterServer.code + ", 'NixiesLake.Server', '0')," +
        "(" + CreaterServer.code + ", 'NixiesLake.StandbyTime', '0')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.RequiredTicket', '5')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Reward', '100')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Score1', '1000')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Score2', '2000')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Score3', '3000')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Score4', '4000')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.Score5', '5000')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.ScoreBall', '100')," +
        "(" + CreaterServer.code + ", 'NumericBaseball.ScoreStrike', '200')," +
        "(" + CreaterServer.code + ", 'OnlyBaseStatForEquipment', '1')," +
        "(" + CreaterServer.code + ", 'Option380.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Option380.Price', '100000')," +
        "(" + CreaterServer.code + ", 'Option380.RateGrade1', '30')," +
        "(" + CreaterServer.code + ", 'Option380.RateGrade2', '20')," +
        "(" + CreaterServer.code + ", 'Option380.RateGrade3', '10')," +
        "(" + CreaterServer.code + ", 'Party.AllowDifGens', '1')," +
        "(" + CreaterServer.code + ", 'Party.AllowPK', '1')," +
        "(" + CreaterServer.code + ", 'Party.BonusExperience2', '100')," +
        "(" + CreaterServer.code + ", 'Party.BonusExperience3', '200')," +
        "(" + CreaterServer.code + ", 'Party.BonusExperience4', '300')," +
        "(" + CreaterServer.code + ", 'Party.BonusExperience5', '400')," +
        "(" + CreaterServer.code + ", 'Party.Enabled', '4')," +
        "(" + CreaterServer.code + ", 'Party.Experience2', '180')," +
        "(" + CreaterServer.code + ", 'Party.Experience3', '260')," +
        "(" + CreaterServer.code + ", 'Party.Experience4', '360')," +
        "(" + CreaterServer.code + ", 'Party.Experience5', '440')," +
        "(" + CreaterServer.code + ", 'Party.InBattlezone', '1')," +
        "(" + CreaterServer.code + ", 'Party.LeaderChange', '1')," +
        "(" + CreaterServer.code + ", 'Party.MatchingEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Party.MatchingLeaderChange', '1')," +
        "(" + CreaterServer.code + ", 'Party.MaxLevelDif', '220')," +
        "(" + CreaterServer.code + ", 'Party.MaxWaitInterval', '0')," +
        "(" + CreaterServer.code + ", 'Party.MemberOfflineInterval', '10')," +
        "(" + CreaterServer.code + ", 'Party.MoveCost', '100')," +
        "(" + CreaterServer.code + ", 'Party.MoveEnabled', '1')," +
        "(" + CreaterServer.code + ", 'PersonalStore.Disconnect', '1')," +
        "(" + CreaterServer.code + ", 'PersonalStore.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'PersonalStore.MinLevel', '1')," +
        "(" + CreaterServer.code + ", 'PersonalStore.Off', '0')," +
        "(" + CreaterServer.code + ", 'PersonalStore.OffCount', '0')," +
        "(" + CreaterServer.code + ", 'PersonalStore.OffDuration', '1')," +
        "(" + CreaterServer.code + ", 'PersonalStore.OffTotalCount', '0')," +
        "(" + CreaterServer.code + ", 'PlayerWalkSpeed', '400')," +
        "(" + CreaterServer.code + ", 'ProtectorOfAcheron.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'QuestMU.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Radiance.BindingDuration', '5')," +
        "(" + CreaterServer.code + ", 'Radiance.BleedingDuration', '10')," +
        "(" + CreaterServer.code + ", 'Radiance.BleedingRate', '5')," +
        "(" + CreaterServer.code + ", 'Radiance.BlindingDuration', '10')," +
        "(" + CreaterServer.code + ", 'Radiance.BlindingRate', '5')," +
        "(" + CreaterServer.code + ", 'Radiance.ParalysisEffect', '90')," +
        "(" + CreaterServer.code + ", 'Radiance.ParalysisRate', '5')," +
        "(" + CreaterServer.code + ", 'Raklion.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Raklion.FailTimeMax', '30')," +
        "(" + CreaterServer.code + ", 'Raklion.FailTimeMin', '25')," +
        "(" + CreaterServer.code + ", 'Raklion.SuccessTimeMax', '15')," +
        "(" + CreaterServer.code + ", 'Raklion.SuccessTimeMin', '6')," +
        "(" + CreaterServer.code + ", 'RareIceDragonRate', '5')," +
        "(" + CreaterServer.code + ", 'Refuge.MoveCost', '1000')," +
        "(" + CreaterServer.code + ", 'Refuge.MoveEnabled', '1')," +
        "(" + CreaterServer.code + ", 'Refuge.MoveMinLevel', '200')," +
        "(" + CreaterServer.code + ", 'Refuge.MoveParty', '1')," +
        "(" + CreaterServer.code + ", 'SantaVillage.CheckSeason', '1')," +
        "(" + CreaterServer.code + ", 'SantaVillage.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'SantaVillage.SantaClaus.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'SantaVillage.SantaClaus.GiftTime', '90')," +
        "(" + CreaterServer.code + ", 'SantaVillage.SantaClaus.ItemBag', '1')," +
        "(" + CreaterServer.code + ", 'SantaVillage.Season', '0')," +
        "(" + CreaterServer.code + ", 'Scramble.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Scramble.RepeatWordCount', '0')," +
        "(" + CreaterServer.code + ", 'Scramble.Reward', '')," +
        "(" + CreaterServer.code + ", 'Scramble.TotalWordCount', '0')," +
        "(" + CreaterServer.code + ", 'SecretShop.List', '')," +
        "(" + CreaterServer.code + ", 'SecretShop.WarpTime', '0')," +
        "(" + CreaterServer.code + ", 'Skill.AbsorbHPRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.AbsorbSDRate', '100')," +
        "(" + CreaterServer.code + ", 'Skill.ArchangelWillDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ArchangelWillDuration', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ArchangelWillSkillDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BastionRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BastionReduction', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BastionSD', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BlindAdd', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BlindDiv', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BlindTime', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BlindValue', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BloodHowlingDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BloodHowlingDuration', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BloodHowlingRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BossDebuffBlow', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BurstRWDurationAdd', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BurstRWDurationDiv', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BurstRWEffect1Div', '0')," +
        "(" + CreaterServer.code + ", 'Skill.BurstRWEffect2Div', '0')," +
        "(" + CreaterServer.code + ", 'Skill.CircleShieldDuration', '0')," +
        "(" + CreaterServer.code + ", 'Skill.CircleShieldReduceAG', '0')," +
        "(" + CreaterServer.code + ", 'Skill.CircleShieldReduceAGRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.CureBuffRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.DarkPlasmaAttackDistance', '8')," +
        "(" + CreaterServer.code + ", 'Skill.DarkPlasmaAttackSpeed', '5')," +
        "(" + CreaterServer.code + ", 'Skill.DarkPlasmaTargetCount', '5')," +
        "(" + CreaterServer.code + ", 'Skill.DetectionRange', '0')," +
        "(" + CreaterServer.code + ", 'Skill.EarthPrisonStunRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ElementalBerserkerI', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ElementalBerserkerIDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ElementalBerserkerIDefense', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ElementalImmuneI', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ElementalImmuneII', '0')," +
        "(" + CreaterServer.code + ", 'Skill.EnergyCheck', '1')," +
        "(" + CreaterServer.code + ", 'Skill.FireScreamExplosionRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.FixPowersOnBuff', '0')," +
        "(" + CreaterServer.code + ", 'Skill.HasteRWDurationAdd', '0')," +
        "(" + CreaterServer.code + ", 'Skill.HasteRWDurationDiv', '0')," +
        "(" + CreaterServer.code + ", 'Skill.HasteRWEffect1Div', '0')," +
        "(" + CreaterServer.code + ", 'Skill.HasteRWEffect2Div', '0')," +
        "(" + CreaterServer.code + ", 'Skill.IllusionDuration', '0')," +
        "(" + CreaterServer.code + ", 'Skill.IronDefenseDuration', '0')," +
        "(" + CreaterServer.code + ", 'Skill.IronDefenseValue1', '0')," +
        "(" + CreaterServer.code + ", 'Skill.IronDefenseValue2', '0')," +
        "(" + CreaterServer.code + ", 'Skill.LeadershipCheck', '1')," +
        "(" + CreaterServer.code + ", 'Skill.MagicArrowProjectiles', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MagicArrowSplashDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MagicArrowSplashDistance', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MagicArrowSplashTargets', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MagicPinExplosionDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MagicPinExplosionRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ManaShieldCastleSiegeLimit', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ManaShieldLimit', '0')," +
        "(" + CreaterServer.code + ", 'Skill.MultiAttackCount', '40')," +
        "(" + CreaterServer.code + ", 'Skill.MultiAttackNew', '1')," +
        "(" + CreaterServer.code + ", 'Skill.MultiAttackTime', '100')," +
        "(" + CreaterServer.code + ", 'Skill.ParalizeDebuffRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallAttackCount', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallAttackDistance', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallAttackSpeed', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallMoveDistance', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallMoveSpeed', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PlasmaBallTargetCount', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PoisonArrowDebuffRate', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishFirstHit', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishFrequencyPVM', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishFrequencyPVP', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishMaxDamage', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishRatePVM', '0')," +
        "(" + CreaterServer.code + ", 'Skill.PunishRatePVP', '0')," +
        "(" + CreaterServer.code + ", 'Skill.ReflectLimit', '25')," +
        "(" + CreaterServer.code + ", 'Skill.SleepLimit', '70')," +
        "(" + CreaterServer.code + ", 'Skill.SleepLimitTime', '70')," +
        "(" + CreaterServer.code + ", 'Skill.SleepReuseTime', '1000')," +
        "(" + CreaterServer.code + ", 'Skill.SplashDamagePercent', '100')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateAttack0', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateAttack1', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateAttack2', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateAttack3', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateRemoveVP0', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateRemoveVP1', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateRemoveVP2', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateRemoveVP3', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateTime0', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateTime1', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateTime2', '0')," +
        "(" + CreaterServer.code + ", 'SkillTeleport.StateTime3', '0')," +
        "(" + CreaterServer.code + ", 'SpecialMap.CharacterCount', '0')," +
        "(" + CreaterServer.code + ", 'SpecialMap.PVP', '0')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.BattleTime', '20')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.BossAppearTime', '15')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.ClosedTimeMax', '30')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.ClosedTimeMin', '5')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'SwampOfDarkness.MaxPlayers', '5')," +
        "(" + CreaterServer.code + ", 'TeleportCoordinateBuff', '57 241')," +
        "(" + CreaterServer.code + ", 'TeleportFix', '1')," +
        "(" + CreaterServer.code + ", 'TeleportRestrictBuff', '61 72 146 147')," +
        "(" + CreaterServer.code + ", 'TormentedSquare.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'TormentedSquareSurvival.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Trade.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'Trade.MaxWaitInterval', '0')," +
        "(" + CreaterServer.code + ", 'Trade.MaxZen', '99999999999')," +
        "(" + CreaterServer.code + ", 'Transaction.DuplicatedSerialDelete', '1')," +
        "(" + CreaterServer.code + ", 'Transaction.SharedDuplicatedSerialDelete', '1')," +
        "(" + CreaterServer.code + ", 'Transfer.Enabled', '0')," +
        "(" + CreaterServer.code + ", 'Transfer.PartyServer', '1')," +
        "(" + CreaterServer.code + ", 'Transfer.Server', '1')," +
        "(" + CreaterServer.code + ", 'WorldBoss.AOERange', '30')," +
        "(" + CreaterServer.code + ", 'WorldBoss.Enabled', '1')," +
        "(" + CreaterServer.code + ", 'WorldBoss.GuildPK', '1')," +
        "(" + CreaterServer.code + ", 'WorldBoss.IncreaseDamagePerPoint', '1000')," +
        "(" + CreaterServer.code + ", 'WorldBoss.ItemBag', '')," +
        "(" + CreaterServer.code + ", 'WorldBoss.MaxPKPoints', '10')," +
        "(" + CreaterServer.code + ", 'WorldBoss.NormalRespawn', '1')," +
        "(" + CreaterServer.code + ", 'WorldBoss.PKGAP', '0')," +
        "(" + CreaterServer.code + ", 'WorldBoss.PKRange', '0')," +
        "(" + CreaterServer.code + ", 'WorldBoss.RequiredPlayer', '1')," +
        "(" + CreaterServer.code + ", 'WorldBoss.RequiredPointsToAttack', '0')," +
        "(" + CreaterServer.code + ", 'WorldBoss.StartNotification', '1');";
    }
}
